/**
 * This code generated by EnjoyHealth
 */
package com.example.entity;

import java.io.Serializable;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * <p>实体类</p>
 * <p>Table: pm_task - 任务表</p>
 * systemUser:
 * Date: 2019-12-30 03:40:41
 */
public class PmsTask implements Serializable {

    /** ID -  */
    private Integer ID;
    
    /** PID - 父任务ID */
    private Integer pid;
    
    /** PROJECT_ID - 项目ID */
    private Integer projectId;
    
    /** NAME - 任务名称 */
    private String name;
    
    /** MARK - 任务描述 */
    private String mark;
    
    /** EXECUTOR_ID - 执行人ID */
    private Integer executorId;
    
    /** CREATE_DATE - 创建时间 */
    private Date createDate;
    
    /** DONE - 完成标志 */
    private String done;
    
    /** FINISH_DATE - 任务结束时间 */
    private Date finishDate;
    
    /** PRIORITY - 优先级 */
    private String priority;
    
    /** SOURCE - 来源 */
    private String source;
    
    /** REMIND_ID - 提醒ID */
    private Integer remindId;
    
    /** ACCEPTED - 认领标志 0:未认领 1:认领 2:拒绝*/
    private String accepted;
    
    /** STAGE_ID - 阶段ID */
    private Integer stageId;
    
    /** DELETED - 删除标志 1:删除 0:其他 */
    private String deleted;

    /** SORT - 排序 */
    private Double sort;

    /** CREATE_ID - 创建人ID */
	private Integer createId;

    /** DONE_DATE - 任务完成时间 */
    private Date doneDate;

    public PmsTask(){
    }

    public PmsTask(Integer ID, String name ,Date createDate) {
        this.ID = ID;
        this.name = name;
        this.createDate = createDate;
    }

    public Integer getID() {
        return ID;
    }

    public void setID(Integer ID) {
        this.ID = ID;
    }

    public Integer getPid() {
        return pid;
    }

    public void setPid(Integer pid) {
        this.pid = pid;
    }

    public Integer getProjectId() {
        return projectId;
    }

    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getMark() {
        return mark;
    }

    public void setMark(String mark) {
        this.mark = mark;
    }

    public Integer getExecutorId() {
        return executorId;
    }

    public void setExecutorId(Integer executorId) {
        this.executorId = executorId;
    }

    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getDone() {
        return done;
    }

    public void setDone(String done) {
        this.done = done;
    }

    public Date getFinishDate() {
        return finishDate;
    }

    public void setFinishDate(Date finishDate) {
        this.finishDate = finishDate;
    }

    public String getPriority() {
        return priority;
    }

    public void setPriority(String priority) {
        this.priority = priority;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public Integer getRemindId() {
        return remindId;
    }

    public void setRemindId(Integer remindId) {
        this.remindId = remindId;
    }

    public String getAccepted() {
        return accepted;
    }

    public void setAccepted(String accepted) {
        this.accepted = accepted;
    }

    public Integer getStageId() {
        return stageId;
    }

    public void setStageId(Integer stageId) {
        this.stageId = stageId;
    }

    public String getDeleted() {
        return deleted;
    }

    public void setDeleted(String deleted) {
        this.deleted = deleted;
    }

    public Double getSort() {
        return sort;
    }

    public void setSort(Double sort) {
        this.sort = sort;
    }

    public Integer getCreateId() {
        return createId;
    }

    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    public Date getDoneDate() {
        return doneDate;
    }

    public void setDoneDate(Date doneDate) {
        this.doneDate = doneDate;
    }

    @Override
    public boolean equals(Object obj) {
        if(this == obj){
            return true;//地址相等
        }

        if(obj == null){
            return false;//非空性：对于任意非空引用x，x.equals(null)应该返回false。
        }

        if(obj instanceof PmsTask){
            PmsTask other = (PmsTask) obj;
            //需要比较的字段相等，则这两个对象相等
            if((this.getID()).equals(other.getID())){
                return true;
            }
        }

        return false;
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (ID == null ? 0 : ID.hashCode());
        return result;
    }

    DateFormat f = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

    @Override
    public String toString() {
        return "PmsTask{" +
                "ID=" + ID +
                ", name='" + name + '\'' +
                ", createDate=" + f.format(createDate) +
                '}';
    }
}